# Generated by Django 5.0.3 on 2024-10-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('proposal_type', models.CharField(choices=[('Research', 'Research'), ('Business', 'Business'), ('Grant', 'Grant')], max_length=50)),
                ('file', models.FileField(upload_to='proposals/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
